# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore ./src/ISRORCert.sln
      - name: Build
        run: dotnet build ./src/ISRORCert.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test ./src/ISRORCert.sln --no-build --verbosity normal
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        id: create_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
      - name: publish_win_x64
        run: dotnet publish ./src/ISRORCert.sln -r win-x64 -c Release --self-contained true -p:PublishReadyToRun=true && tar -czvf ISRORCert_win-x64.tar.gz -C ./src/ISRORCert/bin/Release/net6.0/win-x64/publish ./
      - name: publish_linux_x64
        run: dotnet publish ./src/ISRORCert.sln -r linux-x64 -c Release --self-contained true -p:PublishReadyToRun=true && tar -czvf ISRORCert_linux-x64.tar.gz -C ./src/ISRORCert/bin/Release/net6.0/linux-x64/publish ./

      - name: Create Release
        uses: ncipollo/release-action@v1
        id: create_release
        with:
          artifacts: "ISRORCert_linux-x64.tar.gz,ISRORCert_win-x64.tar.gz"
          tag: ${{ steps.create_tag.outputs.new_tag }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
